config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', controller: :dashboard, action: :show

  namespace :dashboard, as: nil do
    resources :questionnaires, path: "cuestionarios" do
      resources :answered_questionnaires, path: "respuestas", as: :answered
    end

    resources :users, path: "usuarios" do
      resources :questionnaires, path: "cuestionarios", controller: "users/questionnaires"
    end
  end
  devise_for :users
  root to: "home#index"
end

app/models/answered_questionnaire.rb
# == Schema Information
#
# Table name: answered_questionnaires
#
#  id               :integer          not null, primary key
#  questioned       :string
#  profile          :string
#  conclusions      :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  questionnaire_id :integer
#

class AnsweredQuestionnaire < ActiveRecord::Base
  belongs_to :questionnaire
  has_many :answers

  validates :questioned, presence: true

  accepts_nested_attributes_for :answers
end

app/controllers/dashboard/answered_questionnaires_controller.rb
module Dashboard
  class AnsweredQuestionnairesController < DashboardController
    before_action :set_questionnaire
    before_action :set_answered_questionnaire, only: [:show, :edit, :update, :destroy]
    before_action :set_title
    before_action :set_subtitle, only: [:show, :edit, :update, :destroy]

    def index
      @answered_questionnaires = AnsweredQuestionnaire.all
    end

    def show
    end

    def new
      @answered_questionnaire = @questionnaire.answered_questionnaires.new
      @questionnaire.questions.each do |question|
        @answered_questionnaire.answers.new(question: question)
      end
    end

    def edit
    end

    def create
      @answered_questionnaire = @questionnaire.answered_questionnaires.new(answered_questionnaire_params)

      respond_to do |format|
        if @answered_questionnaire.save
          format.html { redirect_to questionnaire_answered_path(@questionnaire, @answered_questionnaire),
                        notice: 'Answered questionnaire was successfully created.' }
          format.json { render :show, status: :created, location: @answered_questionnaire }
        else
          format.html { render :new }
          format.json { render json: @answered_questionnaire.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @answered_questionnaire.update(answered_questionnaire_params)
          format.html { redirect_to @answered_questionnaire, notice: 'Answered questionnaire was successfully updated.' }
          format.json { render :show, status: :ok, location: @answered_questionnaire }
        else
          format.html { render :edit }
          format.json { render json: @answered_questionnaire.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @answered_questionnaire.destroy
      respond_to do |format|
        format.html { redirect_to answered_questionnaires_url, notice: 'Answered questionnaire was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

  private
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:questionnaire_id])
    end

    def set_answered_questionnaire
      @answered_questionnaire = @questionnaire.answered_questionnaires.find(params[:id])
    end

    def set_title
      @title = @questionnaire.decorate.title
    end

    def set_subtitle
      @subtitle = "Respuestas"
    end

    def answered_questionnaire_params
      params.require(:answered_questionnaire).permit(:questioned, :profile,
        :conclusions, answers_attributes: [:value, :question_id])
    end
  end
end

app/controllers/dashboard/answers_controller.rb
module Dashboard
  class AnswersController < ApplicationController

    def index
      @answers = Answer.all
    end

  end
end

app/controllers/dashboard/questionnaires_controller.rb
module Dashboard
  class QuestionnairesController < DashboardController
    before_action :set_questionnaire, except: [:index, :new, :create]

    def index
      @questionnaires = Questionnaire.all
    end

    def new
      @questionnaire = current_user.questionnaires.new
      @questionnaire.questions.build
    end

    def create
      @questionnaire = current_user.questionnaires.new(questionnaire_params)
      if @questionnaire.save
        return redirect_to @questionnaire,
                           notice: "Se ha creado el Cuestionario exitosamente."
      end

      render :new
    end

    def show; end
    def edit; end

    def update
      if @questionnaire.update(questionnaire_params)
        return redirect_to [:dashboard, @questionnaire],
                           notice: "Se ha modificado el Cuestionario #{@questionnaire.name} exitosamente."
      end

      render :edit
    end

    def destroy
      @questionnaire.destroy
      redirect_to dashboard_questionnaires_path,
                  notice: "El Cuestionario #{@questionnaire.name} ha sido elimnado completamente incluyendo sus Preguntas"
    end

    protected

    def set_title
      @title = "Mis Cuestionarios"
    end

    private

    def questionnaire_params
      params.require(:questionnaire).permit(:name, :close_at,
        questions_attributes: [:id, :text, :_destroy])
    end

    def set_questionnaire
      @questionnaire = Questionnaire.includes(:questions).find(params[:id])
      @title         = @questionnaire.decorate.title
    end
  end
end

app/controllers/dashboard/questions_controller.rb
class QuestionsController < ApplicationController
end

app/controllers/dashboard/users/questionnaires_controller.rb
module Dashboard
  module Users
    class QuestionnairesController < DashboardController
      before_action :set_user
      before_action :set_title

      def index
        @questionnaires = @user.questionnaires
      end

      private

      def set_user
        @user = User.find(params[:user_id])
      end

      def set_title
        @title = "Cuestionarios de #{@user.decorate}"
      end
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :set_title
  before_action :set_subtitle

  layout "dashboard"

  def show
  end

  protected

  def set_title
    @title = params[:controller].titleize
  end

  def set_subtitle
    @subtitle = params[:action].titleize
  end
end

app/helpers/answered_questionnaires_helper.rb
module AnsweredQuestionnairesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/answered_questionnaires/_form.html.erb
<%= form_for @answered_questionnaire, url: creation_path, html: {class: "form-horizontal"} do |f| %>
  <div class="box-body">
    <% if @answered_questionnaire.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@answered_questionnaire.errors.count, "error") %> prohibited this answered_questionnaire from being saved:</h2>

        <ul>
        <% @answered_questionnaire.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <legend>Detalle</legend>

    <div class="form-group">
      <%= f.label :questioned, "Cuestionado", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :questioned, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :profile, "Perfil del Cuestionado", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :profile, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :conclusions, "Conclusiones", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_area :conclusions, class: "form-control" %>
      </div>
    </div>

    <legend>Respuestas</legend>

    <% @answered_questionnaire.answers.each do |answer| %>
      <div class="form-group">
        <%= f.fields_for :answers, answer do |af| %>
          <%= af.hidden_field :question_id %>
          <%= af.label :question, class: "col-sm-12" do %>
            <%= af.index + 1 %>.
            ¿<%= answer.question.text %>?
          <% end %>

          <%= f.label :value, class: "col-md-offset-1 col-sm-1" do %>
            <%= af.radio_button :value, "Si" %> Si
          <% end %>
          <%= f.label :value, class: "col-sm-1" do %>
            <%= af.radio_button :value, "No" %> No
          <% end %>

        <% end %>
      </div>
    <% end %>
  </div>

  <div class="box-footer">
    <%= f.submit "Enviar", class: "btn btn-primary pull-right" %>
    <%= link_to "Volver", :back, class: "btn btn-default" %>
  </div>
<% end %>

app/views/dashboard/answered_questionnaires/edit.html.erb
<h1>Editing Answered Questionnaire</h1>

<%= render 'form', form_path: questionnaire_answered_path %>

<%= link_to 'Show', @answered_questionnaire %> |
<%= link_to 'Back', answered_questionnaires_path %>

app/views/dashboard/answered_questionnaires/index.html.erb
<h1>Respuestas al Cuestionarios <%= @questionnaire.name %></h1>

<%= link_to 'New Answered questionnaire', new_questionnaire_answered_path(@questionnaire) %>
<table>
  <thead>
    <tr>
      <th>Cuestionado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answered_questionnaires.each do |answered_questionnaire| %>
      <tr>
        <td><%= answered_questionnaire.questioned %></td>
        <td><%= link_to 'Show', questionnaire_answered_path(@questionnaire, answered_questionnaire) %></td>
        <td><%= link_to 'Edit', edit_questionnaire_answered_path(@questionnaire, answered_questionnaire) %></td>
        <td><%= link_to 'Destroy', questionnaire_answered_path(@questionnaire, answered_questionnaire), method: :delete, data: { confirm: '¿Está usted seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboard/answered_questionnaires/new.html.erb
<div class="box box-default">
  <%= render 'form', creation_path: questionnaire_answered_index_path() %>
</div>

app/views/dashboard/answered_questionnaires/show.html.erb
<nav class="navbar navbar-default options">
  <ul class="nav nav-pills">
    <li role="presentation">
      <%= link_to edit_questionnaire_answered_path(@questionnaire, @answered_questionnaire) do %>
        <i class="fa fa-edit"></i>
        Editar
      <% end %>
    </li>
    <li role="presentation">
      <%= link_to questionnaire_answered_path, method: :delete, confirm: "¿Está usted seguro?" do %>
        <i class="fa fa-trash"></i>
        Eliminar
      <% end %>
    </li>
  </ul>
</nav>

<div class="box box-primary">
  <div class="box-header">
    <h3 class="box-title">Detalle</h3>
  </div>
  <div class="box-body">
    <dl class="dl-horizontal">
      <dt>Cuestionado:</dt>
      <dd><%= @answered_questionnaire.questioned %></dd>
      <dt>Perfil del Cuestionado:</dt>
      <dd><%= @answered_questionnaire.profile %></dd>
      <dt>Conclusiones:</dt>
      <dd><%= @answered_questionnaire.conclusions %></dd>
    </dl>
  </div>
</div>

<div class="box box-default">
  <div class="box-header">
    <h3 class="box-title">Respuestas</h3>
  </div>
  <div class="box-body">
    <ol>
      <% @answered_questionnaire.answers.each_with_index do |answer, index| %>
        <li><%= answer.question.text %> <br> <strong><%= answer.value %></strong></li>
      <% end %>
    </ol>
  </div>
</div>