config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', controller: :dashboard, action: :show

  namespace :dashboard, as: nil do
    resources :questionnaires, path: "cuestionarios" do
      resources :answered_questionnaires, path: "respuestas", as: :answered
    end

    resources :users, path: "usuarios" do
      resources :questionnaires, path: "cuestionarios", controller: "users/questionnaires"
    end
  end
  devise_for :users
  root to: "home#index"
end

app/models/questionnaire.rb
# == Schema Information
#
# Table name: questionnaires
#
#  id         :integer          not null, primary key
#  name       :string
#  state      :integer
#  close_at   :datetime
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Questionnaire < ActiveRecord::Base
  belongs_to :user
  has_many :questions, dependent: :destroy
  has_many :answered_questionnaires, dependent: :destroy

  validates :name, :questions, presence: true

  accepts_nested_attributes_for :questions, allow_destroy: true,
                                            reject_if: :all_blank

  delegate :count, to: :answered_questionnaires, prefix: true
  delegate :count, to: :questions, prefix: true

end

app/controllers/dashboard/answered_questionnaires_controller.rb
module Dashboard
  class AnsweredQuestionnairesController < DashboardController
    before_action :set_questionnaire
    before_action :set_answered_questionnaire, only: [:show, :edit, :update, :destroy]
    before_action :set_title
    before_action :set_subtitle, only: [:show, :edit, :update, :destroy]

    def index
      @answered_questionnaires = AnsweredQuestionnaire.all
    end

    def show
    end

    def new
      @answered_questionnaire = @questionnaire.answered_questionnaires.new
      @questionnaire.questions.each do |question|
        @answered_questionnaire.answers.new(question: question)
      end
    end

    def edit
    end

    def create
      @answered_questionnaire = @questionnaire.answered_questionnaires.new(answered_questionnaire_params)

      respond_to do |format|
        if @answered_questionnaire.save
          format.html { redirect_to questionnaire_answered_path(@questionnaire, @answered_questionnaire),
                        notice: 'Answered questionnaire was successfully created.' }
          format.json { render :show, status: :created, location: @answered_questionnaire }
        else
          format.html { render :new }
          format.json { render json: @answered_questionnaire.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @answered_questionnaire.update(answered_questionnaire_params)
          format.html { redirect_to @answered_questionnaire, notice: 'Answered questionnaire was successfully updated.' }
          format.json { render :show, status: :ok, location: @answered_questionnaire }
        else
          format.html { render :edit }
          format.json { render json: @answered_questionnaire.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @answered_questionnaire.destroy
      respond_to do |format|
        format.html { redirect_to answered_questionnaires_url, notice: 'Answered questionnaire was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

  private
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:questionnaire_id])
    end

    def set_answered_questionnaire
      @answered_questionnaire = @questionnaire.answered_questionnaires.find(params[:id])
    end

    def set_title
      @title = @questionnaire.decorate.title
    end

    def set_subtitle
      @subtitle = "Respuestas"
    end

    def answered_questionnaire_params
      params.require(:answered_questionnaire).permit(:questioned, :profile,
        :conclusions, answers_attributes: [:value, :question_id])
    end
  end
end

app/controllers/dashboard/answers_controller.rb
module Dashboard
  class AnswersController < ApplicationController

    def index
      @answers = Answer.all
    end

  end
end

app/controllers/dashboard/questionnaires_controller.rb
module Dashboard
  class QuestionnairesController < DashboardController
    before_action :set_questionnaire, except: [:index, :new, :create]

    def index
      @questionnaires = Questionnaire.all
    end

    def new
      @questionnaire = current_user.questionnaires.new
      @questionnaire.questions.build
    end

    def create
      @questionnaire = current_user.questionnaires.new(questionnaire_params)
      if @questionnaire.save
        return redirect_to @questionnaire,
                           notice: "Se ha creado el Cuestionario exitosamente."
      end

      render :new
    end

    def show; end
    def edit; end

    def update
      if @questionnaire.update(questionnaire_params)
        return redirect_to [:dashboard, @questionnaire],
                           notice: "Se ha modificado el Cuestionario #{@questionnaire.name} exitosamente."
      end

      render :edit
    end

    def destroy
      @questionnaire.destroy
      redirect_to dashboard_questionnaires_path,
                  notice: "El Cuestionario #{@questionnaire.name} ha sido elimnado completamente incluyendo sus Preguntas"
    end

    protected

    def set_title
      @title = "Mis Cuestionarios"
    end

    private

    def questionnaire_params
      params.require(:questionnaire).permit(:name, :close_at,
        questions_attributes: [:id, :text, :_destroy])
    end

    def set_questionnaire
      @questionnaire = Questionnaire.includes(:questions).find(params[:id])
      @title         = @questionnaire.decorate.title
    end
  end
end

app/controllers/dashboard/questions_controller.rb
class QuestionsController < ApplicationController
end

app/controllers/dashboard/users/questionnaires_controller.rb
module Dashboard
  module Users
    class QuestionnairesController < DashboardController
      before_action :set_user
      before_action :set_title

      def index
        @questionnaires = @user.questionnaires
      end

      private

      def set_user
        @user = User.find(params[:user_id])
      end

      def set_title
        @title = "Cuestionarios de #{@user.decorate}"
      end
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :set_title
  before_action :set_subtitle

  layout "dashboard"

  def show
  end

  protected

  def set_title
    @title = params[:controller].titleize
  end

  def set_subtitle
    @subtitle = params[:action].titleize
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/views/dashboard/questionnaires/_form.html.erb
<%= form_for questionnaire, html: {class: "form-horizontal"} do |f| %>
  <div class="box-body">
    <div class="errors">
      <% questionnaire.errors.full_messages.each do |error| %>
        <%= error.inspect %>
      <% end %>
    </div>

    <legend>Detalle</legend>
    <div class="form-group">
      <%= f.label :name, "Nombre", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control", placeholder: "Nombre del Cuestionario" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :close_at, "Fecha de Cierre", class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.date_field :close_at, class: "form-control" %>
      </div>
    </div>

    <legend>Lista de Preguntas</legend>
    <div id="questions">
      <%= f.fields_for :questions do |question| %>
        <%= render 'question_fields', f: question %>
      <% end %>
      <div class="links">
        <%= link_to_add_association 'Agregar Pregunta', f, :questions, class: "btn btn-default pull-right" %>
      </div>
    </div>
  </div>
  <div class="box-footer">
    <%= f.submit class: "btn btn-info pull-right" %>
    <%= link_to "Volver", :back, class: "btn btn-default" %>
  </div>
<% end %>

app/views/dashboard/questionnaires/_question_fields.html.erb
<div class="nested-fields form-group">
  <%= f.label :text, "Pregunta", class: "col-sm-2 control-label" %>
  <div class="col-sm-10">
    <div class="input-group">
      <%= f.text_field :text, class: "form-control" %>
      <span class="input-group-addon">
        <i class="fa fa-question"></i>
      </span>
      <span class="input-group-addon btn btn-danger">
        <%= link_to_remove_association f do %>
          <i class="fa fa-trash"></i>
        <% end %>
      </span>
    </div>
  </div>
</div>

app/views/dashboard/questionnaires/edit.html.erb
<h1>Editar Cuestionario <%= @questionnaire.name %></h1>

<%= render "form", questionnaire: @questionnaire %>

app/views/dashboard/questionnaires/index.html.erb
<nav class="navbar navbar-default options">
  <ul class="nav nav-pills">
    <li role="presentation">
      <%= link_to new_questionnaire_path do %>
        <i class="fa fa-file"></i>
        Nuevo Cuestionario
      <% end %>
    </li>
  </ul>
</nav>

<div class="panel panel-default">
  <table class="table">
    <thead>
      <td>Nombre</td>
      <td>No. Preguntas</td>
      <td>No. Respuestas</td>
      <td>Creador</td>
      <td>Fecha de Cierre</td>
      <td>Fecha de Creación</td>
      <td></td>
    </thead>
    <tbody>
      <% @questionnaires.decorate.each do |questionnaire| %>
        <tr>
          <td><%= questionnaire.name %></td>
          <td><%= questionnaire.questions_count %></td>
          <td><%= questionnaire.answered_questionnaires_count %></td>
          <td><%= questionnaire.user %></td>
          <td><%= questionnaire.close_at %></td>
          <td><%= questionnaire.created_at %></td>
          <td>
            <%= link_to [questionnaire], class: "btn btn-link" do %>
              <i class="fa fa-eye"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/dashboard/questionnaires/new.html.erb
<div class="box box-default">
  <%= render "form", questionnaire: @questionnaire %>
</div>

app/views/dashboard/questionnaires/show.html.erb
<nav class="navbar navbar-default options">
  <ul class="nav nav-pills">
    <li role="presentation">
      <%= link_to new_questionnaire_answered_path(@questionnaire) do %>
        <i class="fa fa-check-square-o"></i>
        Responder
      <% end %>
    </li>
  </ul>
</nav>

<div class="box box-default">
  <div class="box-header">
    <h3 class="box-title">Preguntas</h3>
  </div>
  <div class="box-body">
    <ol>
      <% @questionnaire.questions.each do |question| %>
        <li class="question" data-yes="<%= question.count_answers_with('Si') %>" data-no="<%= question.count_answers_with('No') %>">¿<%= question.text %>?</li>
      <% end %>
    </ol>
  </div>
</div>

<div class="box box-success">
  <div class="box-header">
    <h3 class="box-title">Respuestas</h3>
  </div>
  <div class="box-body">
    <div class="chart">
      <canvas id="bar-chart-answer"></canvas>
    </div>
  </div>
</div>